import { Budget, Client, CompanyProfile, AppNotification, UserAccount } from '../types/database';

export const initialCompany: CompanyProfile = {
  id: 'comp_01',
  user_id: 'user_01',
  name: 'EletroVolt Soluções Elétricas',
  document: '42.123.456/0001-89',
  phone: '(11) 98765-4321',
  whatsapp: '5511987654321',
  email: 'contato@eletrovolt.com.br',
  address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
  website: 'https://eletrovolt.com.br',
  instagram: '@eletrovoltoficial',
  logo_url: '',
  primary_color: '#10b981',
  default_template: 'modern',
  default_whatsapp_message: 'Olá, {cliente}! 👋\n\nPreparei seu orçamento pelo OrçaCerto com todos os detalhes do serviço.\n\n📄 Orçamento {numero}\n💰 Valor total: {valor}\n\nFico à disposição para esclarecer qualquer dúvida ou já combinarmos o início do projeto!',
  pix_key: 'contato@eletrovolt.com.br',
  pix_key_type: 'email',
};

export const initialClients: Client[] = [
  {
    id: 'cli_01',
    user_id: 'user_01',
    name: 'João da Silva',
    document: '123.456.789-00',
    email: 'joao.silva@email.com',
    phone: '(11) 99876-5432',
    whatsapp: '5511998765432',
    address: 'Rua das Flores, 142 - Moema, São Paulo - SP',
    notes: 'Cliente residencial, prefere atendimento aos sábados pela manhã.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'cli_02',
    user_id: 'user_01',
    name: 'Dra. Mariana Costa',
    document: '987.654.321-11',
    email: 'dra.mariana@clinicacosta.com.br',
    phone: '(11) 97123-8899',
    whatsapp: '5511971238899',
    address: 'Rua Bela Cintra, 850 - Consolação, São Paulo - SP',
    notes: 'Consultório odontológico, reforma de iluminação LED e tomadas cirúrgicas.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'cli_03',
    user_id: 'user_01',
    name: 'Studio Nova Arquitetura',
    document: '18.999.888/0001-22',
    email: 'projetos@studionova.arq.br',
    phone: '(11) 98222-3344',
    whatsapp: '5511982223344',
    address: 'Av. Brigadeiro Faria Lima, 2000 - Itaim Bibi, São Paulo - SP',
    notes: 'Parceiro recorrente para obras comerciais.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: 'cli_04',
    user_id: 'user_01',
    name: 'Roberto Mendes',
    document: '333.444.555-66',
    email: 'roberto.mendes@gmail.com',
    phone: '(11) 99111-2233',
    whatsapp: '5511991112233',
    address: 'Alameda Santos, 450 - Jardins, São Paulo - SP',
    notes: 'Instalação de quadro de disjuntores e aterramento.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
];

export const initialBudgets: Budget[] = [
  {
    id: 'bud_01',
    user_id: 'user_01',
    budget_number: '#000482',
    title: 'Instalação elétrica residencial e iluminação embutida',
    client_id: 'cli_01',
    client: initialClients[0],
    items: [
      {
        id: 'item_01',
        description: 'Mão de obra para revisão de quadro geral e passagem de fiação para novos circuitos de ar-condicionado',
        quantity: 1,
        unit_price: 1500,
        discount: 0,
        total: 1500,
      },
      {
        id: 'item_02',
        description: 'Fornecimento de disjuntores bipolares DIN 25A e fiação antichama 4mm² (rolo 100m)',
        quantity: 1,
        unit_price: 350,
        discount: 0,
        total: 350,
      },
    ],
    subtotal: 1850,
    discount_total: 0,
    total: 1850,
    validity_days: 10,
    payment_method: 'pix',
    payment_terms: '50% de entrada no início e 50% na conclusão e testes',
    execution_time: '2 dias úteis',
    notes: 'Garantia de 90 dias sobre a instalação elétrica. Todos os materiais são homologados pelo Inmetro.',
    warranty: '90 dias contra defeitos de montagem',
    template_id: 'modern',
    primary_color: '#10b981',
    show_signature: true,
    signature_name: 'Carlos Eduardo Volt',
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    sent_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    views_count: 3,
    last_follow_up: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'bud_02',
    user_id: 'user_01',
    budget_number: '#000481',
    title: 'Adequação de tomadas cirúrgicas e iluminação fria clínica',
    client_id: 'cli_02',
    client: initialClients[1],
    items: [
      {
        id: 'item_03',
        description: 'Instalação de canaletas de alumínio com tomadas duplas 20A aterradas',
        quantity: 4,
        unit_price: 450,
        discount: 0,
        total: 1800,
      },
      {
        id: 'item_04',
        description: 'Substituição de 8 luminárias tubulares por painéis LED 60x60 embutidos',
        quantity: 8,
        unit_price: 200,
        discount: 200,
        total: 1400,
      },
    ],
    subtotal: 3400,
    discount_total: 200,
    total: 3200,
    validity_days: 15,
    payment_method: 'card',
    payment_terms: 'Parcelado em até 3x sem juros no cartão de crédito',
    execution_time: '1 final de semana (sábado e domingo)',
    notes: 'Serviço executado fora do horário de atendimento do consultório para não impactar pacientes.',
    warranty: '12 meses para os painéis LED e 90 dias para mão de obra',
    template_id: 'elegant',
    primary_color: '#059669',
    show_signature: true,
    signature_name: 'Carlos Eduardo Volt',
    status: 'approved',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 38).toISOString(),
    sent_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    approved_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 38).toISOString(),
    views_count: 5,
  },
  {
    id: 'bud_03',
    user_id: 'user_01',
    budget_number: '#000480',
    title: 'Projeto luminotécnico para estúdio de design',
    client_id: 'cli_03',
    client: initialClients[2],
    items: [
      {
        id: 'item_05',
        description: 'Instalação de trilhos eletrificados pretos com 16 spots direcionais orientáveis',
        quantity: 4,
        unit_price: 950,
        discount: 100,
        total: 3700,
      },
      {
        id: 'item_06',
        description: 'Automação inteligente de cenas de luz via smartphone e assistente de voz',
        quantity: 1,
        unit_price: 1100,
        discount: 0,
        total: 1100,
      },
    ],
    subtotal: 4900,
    discount_total: 100,
    total: 4800,
    validity_days: 7,
    payment_method: 'pix',
    payment_terms: 'PIX com 5% de desconto à vista ou 2x via transferência',
    execution_time: '4 dias úteis',
    notes: 'Equipamentos e automação com garantia do fabricante Sonoff/Tuya.',
    warranty: '1 ano',
    template_id: 'minimalist',
    primary_color: '#0f172a',
    show_signature: true,
    signature_name: 'Carlos Eduardo Volt',
    status: 'sent',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    sent_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    views_count: 1,
  },
  {
    id: 'bud_04',
    user_id: 'user_01',
    budget_number: '#000479',
    title: 'Troca de fiação e aterramento residencial',
    client_id: 'cli_04',
    client: initialClients[3],
    items: [
      {
        id: 'item_07',
        description: 'Haste de aterramento de cobre com caixa de inspeção e medição de resistência',
        quantity: 1,
        unit_price: 650,
        discount: 0,
        total: 650,
      },
    ],
    subtotal: 650,
    discount_total: 0,
    total: 650,
    validity_days: 10,
    payment_method: 'money',
    payment_terms: 'À vista na conclusão',
    execution_time: '1 dia',
    notes: 'Inclui laudo simplificado de conformidade com a NBR 5410.',
    warranty: '90 dias',
    template_id: 'modern',
    primary_color: '#10b981',
    show_signature: false,
    status: 'draft',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    views_count: 0,
  },
  {
    id: 'bud_05',
    user_id: 'user_01',
    budget_number: '#000478',
    title: 'Manutenção preventiva em bomba de recalque predial',
    client_id: 'cli_01',
    client: initialClients[0],
    items: [
      {
        id: 'item_08',
        description: 'Revisão de comando elétrico com chave boia e contatora Siemens',
        quantity: 1,
        unit_price: 890,
        discount: 0,
        total: 890,
      },
    ],
    subtotal: 890,
    discount_total: 0,
    total: 890,
    validity_days: 5,
    payment_method: 'boleto',
    payment_terms: 'Boleto bancário para 15 dias',
    execution_time: 'Imediato',
    notes: 'Orçamento não aprovado pelo condomínio a tempo.',
    warranty: '90 dias',
    template_id: 'modern',
    primary_color: '#10b981',
    show_signature: true,
    signature_name: 'Carlos Eduardo Volt',
    status: 'expired',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    sent_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    views_count: 2,
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif_01',
    user_id: 'user_01',
    title: 'Orçamento aprovado 🎉',
    message: 'Dra. Mariana Costa aprovou o orçamento #000481 no valor de R$ 3.200,00!',
    type: 'budget_approved',
    is_read: false,
    link: '/orcamentos/bud_02',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'notif_02',
    user_id: 'user_01',
    title: 'Cliente visualizou seu orçamento',
    message: 'Studio Nova Arquitetura abriu o orçamento #000480 agora há pouco.',
    type: 'budget_viewed',
    is_read: false,
    link: '/orcamentos/bud_03',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'notif_03',
    user_id: 'user_01',
    title: '💡 Hora de fazer um follow-up',
    message: 'João da Silva ainda não respondeu ao orçamento #000482 enviado há 2 dias.',
    type: 'follow_up',
    is_read: true,
    link: '/orcamentos/bud_01',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const initialUser: UserAccount = {
  id: 'user_01',
  name: 'Carlos Eduardo',
  email: 'carlos@eletrovolt.com.br',
  company_name: 'EletroVolt Soluções Elétricas',
  phone: '(11) 98765-4321',
  document: '42.123.456/0001-89',
  plan: 'free',
  monthly_budget_limit: 3,
  paid_subscription: false,
  subscription_status: 'inactive',
  created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
};
